### ISSUE TITLE
Getting rid of warnings in debug.txt

### ISSUE THREAD

**Issue by birdlover32767** [ChefZander/skyblock_zero#26]
* ~~`ERROR[Main]: generateImagePart(): Could not load image "pipeworks_autocrafter.png" while building texture; Creating a dummy image`: #25 solves this (and introduces this)~~
* ~~`WARNING[Server]: Undeclared global variable "player_name" accessed at ...n\..\games\skyblock_zero\mods\sbz_resources/organics.lua:21`: this will be solved when zander adds organic stuff but it's just a bit annoying~~ essentially done by #28
* `WARNING[OpenALSoundManager]: OpenALSoundManager::createPlayingSound: Creating positional stereo sound "machine_build.ogg".` and `WARNING[OpenALSoundManager]: OpenALSoundManager::createPlayingSound: Creating positional stereo sound "machine_open.ogg".`: just convert them to mono
* `WARNING[Server]: Deprecated "hud_elem_type" field, use "type" instead. (at .....\games\skyblock_zero\mods\sbz_meteorites/waypoints.lua:53 and 63)`: just rename the `hud_elem_type` to `type`
* `WARNING[OpenALSoundManager]: OpenALSoundManager::createPlayingSound: Creating positional stereo sound "alarm.ogg".`: make it mono

**Comment by TheEt1234** [comment]
> ERROR[Main]: generateImagePart(): Could not load image "pipeworks_autocrafter.png" while building texture; Creating a dummy image: https://github.com/ChefZander/skyblock_zero/issues/25 solves this
*Introduces it

**Comment by TheEt1234** [comment]
> WARNING[OpenALSoundManager]: OpenALSoundManager::createPlayingSound: Creating positional stereo sound "machine_build.ogg". and WARNING[OpenALSoundManager]: OpenALSoundManager::createPlayingSound: Creating positional stereo sound "machine_open.ogg".: just convert them to mono

?

**Comment by TheEt1234** [comment]
do i have to censor the word "fix" in my commit messages so that github doesnt do that

**Comment by TheEt1234** [comment]
,_,

**Comment by TheEt1234** [comment]
ive also included a simple script (convert_sound_to_mono.sh) that can be used in bulk with `find . -name '*.ogg' -exec ~/.minetest/games/skyblock_zero/convert_sound_to_mono.sh {} \;`
