### ISSUE TITLE
Default rotation of Filter-Injector off by a quarter

### ISSUE THREAD

**Issue by ancientmarinerdev** [ChefZander/skyblock_zero#30]
If i face a block, and place the Filter-Injector, it points to my left. It should be logical and either place facing what I'm pointing at, or away from it.

It's a bit illogical and does confuse you when you're trying to get the right rotation.

Btw, the animated texture is stunning.

**Comment by TheEt1234** [comment]
> Btw, the animated texture is stunning.
btw theres a small inaccuracy in the animated texture that ive tried to fix but i couldnt, i think i will let you figure out yourself

**Comment by TheEt1234** [comment]
no way first attempt worked (i just did node.param2 = node.param2 + 1 for testing and it actually turned it correctly?)

**Comment by birdlover32767** [comment]
frog i fixed your inaccuracy for you
![filter_side](https://github.com/user-attachments/assets/0bb4c429-0061-4b26-81d9-eea214cc0672)

**Comment by TheEt1234** [comment]
> frog i fixed your inaccuracy for you ![filter_side](https://private-user-images.githubusercontent.com/162155761/363418316-0bb4c429-0061-4b26-81d9-eea214cc0672.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMTM3NjksIm5iZiI6MTcyNTExMzQ2OSwicGF0aCI6Ii8xNjIxNTU3NjEvMzYzNDE4MzE2LTBiYjRjNDI5LTAwNjEtNGIyNi04MWQ5LWVlYTIxNGNjMDY3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQxNDExMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGJjYzdiZWZiYzQzNzRiYjI0YTE5MDdjZTQ0ODM0MDhjYzUyODdjMTVjMjAyNTQxNmUzMWM1ZjAzNDZiYjdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rP6gPXcJAej5IQuqF3lnQHYBPDvjZms9bF7Ykj-63P8)

oh nice (you can submit a pr after #28 and general improvements get merged )

**Comment by TheEt1234** [comment]
oh you did submit it in your PR ok
