### ISSUE TITLE
Auto-crafter issues

### ISSUE THREAD

**Issue by ancientmarinerdev** [ChefZander/skyblock_zero#31]
Screenshots attached to demonstrate the power supplied and it not powered:

![Screenshot_20240828_223952](https://github.com/user-attachments/assets/e368c1ba-9e1c-4452-93aa-c4a6faf60222)
![Screenshot_20240828_223944](https://github.com/user-attachments/assets/85ad8e0a-b8a3-48d3-84ff-75feab9b434c)

**Comment by ancientmarinerdev** [comment]
Actually. A mistake. It was manually set to 0 power. I think it probably needs to default to 1. The first consumer created that doesn't default to working when connected to the grid.

**Comment by ancientmarinerdev** [comment]
When you feed it a full amount of items, in my case matter dust, the last item in the grid will just swap between 2 numbers:

256 -> 247 -> 256 -> 247 etc.

While the storinator providing it seems to alternate between numbers like follows:

97 -> 70 -> 10 -> ??? -> 44 -> 37 -> 10

**Comment by TheEt1234** [comment]
> Actually. My mistake. It was manually set to 0 power. I think it probably needs to default to 1. The first consumer created that doesn't default to working when connected to the grid.

yeah you can adjust the speed with that, if you set it to 9999 you can craft *very very fast*

**Comment by TheEt1234** [comment]
> When you feed it a full amount of items, in my case matter dust, the last item in the grid will just swap between 2 numbers:
> 
> 256 -> 247 -> 256 -> 247 etc.
> 
> While the storinator providing it seems to alternate between numbers like follows:
> 
> 97 -> 70 -> 10 -> ??? -> 44 -> 37 -> 10

wait whqt

**Comment by TheEt1234** [comment]
> When you feed it a full amount of items, in my case matter dust, the last item in the grid will just swap between 2 numbers:
> 
> 256 -> 247 -> 256 -> 247 etc.
> 
> While the storinator providing it seems to alternate between numbers like follows:
> 
> 97 -> 70 -> 10 -> ??? -> 44 -> 37 -> 10

Ok so whats going on here?

**Comment by TheEt1234** [comment]
@ancientmarinerdev is this solved?

**Comment by ancientmarinerdev** [comment]
> > When you feed it a full amount of items, in my case matter dust, the last item in the grid will just swap between 2 numbers:
> > 256 -> 247 -> 256 -> 247 etc.
> > While the storinator providing it seems to alternate between numbers like follows:
> > 97 -> 70 -> 10 -> ??? -> 44 -> 37 -> 10
> 
> Ok so whats going on here?

I think it's the way the auto injector seems to take items and bounce them back and forward and back and forward. It's weird. It shouldn't take more than it's ready to process.

The default power chance you made looked good, so I think most of my issues are resolved, but it's still weird, and others will probably comment on it also.

**Comment by TheEt1234** [comment]
> > > When you feed it a full amount of items, in my case matter dust, the last item in the grid will just swap between 2 numbers:
> > > 256 -> 247 -> 256 -> 247 etc.
> > > While the storinator providing it seems to alternate between numbers like follows:
> > > 97 -> 70 -> 10 -> ??? -> 44 -> 37 -> 10
> > 
> > Ok so whats going on here?
> 
> I think it's the way the auto injector seems to take items and bounce them back and forward and back and forward. It's weird. It shouldn't take more than it's ready to process.
> 
> The default power chance you made looked good, so I think most of my issues are resolved, but it's still weird, and others will probably comment on it also.

you can mitigate this by giving the automatic filter injector 2 items, and checking `exact match` i think

**Comment by ChefZander** [comment]
Is this resolved?

**Comment by TheEt1234** [comment]
> Is this resolved?

i dont know whats the issue lol
