### ISSUE TITLE
General improvements

### ISSUE THREAD

**Issue by TheEt1234** [ChefZander/skyblock_zero#32]
For my next pr im planning to:
- make multiplayer better (adding homes, tpr and protections) - :white_check_mark: 
- fix bugs - :white_check_mark:  - fixed all issues that there currently are

# New content
- antimatter generator (1 antimatter + 1 matter)/s => 120 power, keep in mind that is PER SECOND, and also it's basically 2 matter + 1 core dust/s => 120 power - :white_check_mark: 

# Potential new content
- better switching station ticking system - :x: Feels like too much work for little gain
- fluid transport - :x: - solid color nodes can look like fluids in tubes, the stack size of fluids could be set to one, also this will require waiting on #28 (which i will probably do)
- emittrium reactor - :x: - needs a coolant loop, that can't be done as there aren't really liquids right now
- finishing what zander just didnt finish (probably burnout) - ingots - :white_check_mark:

**Comment by birdlover32767** [comment]
if you are going to add fluids then make an electrolyzer (e.g splits water into hydrogen and oxygen)

**Comment by TheEt1234** [comment]
> if you are going to add fluids then make an electrolyzer (e.g splits water into hydrogen and oxygen)

im not gonna add fluids in that PR
