### ISSUE TITLE
Tubes have gone crazy

### ISSUE THREAD

**Issue by ancientmarinerdev** [ChefZander/skyblock_zero#36]
Ok, so this is weird. This setup, the corner turned from this to red, so I replaced it with a tube and it went back to how I wanted it.

![Screenshot_20240901_222356](https://github.com/user-attachments/assets/f3978d44-73b1-4001-a921-1a274ab8a037)

Fine so far, right, however, now, when the crusher completes, it sometimes puts the ores in the pebbles slot, and then the pebbles just bounce around the tubes aimlessly until they clip outside the tubes and just head away as can be seen in the picture.

So there is a crusher bug, with other weirdness in there also.

**Comment by ancientmarinerdev** [comment]
More weirdness:

![Screenshot_20240901_223518](https://github.com/user-attachments/assets/e1581049-9d69-42e9-98ac-4e9403091b3d)
![Screenshot_20240901_223502](https://github.com/user-attachments/assets/4d67b49f-15e8-4447-9a8d-cbec941e4c6a)

**Comment by TheEt1234** [comment]
> More weirdness:
> 
> ![Screenshot_20240901_223518](https://private-user-images.githubusercontent.com/114887286/363520726-e1581049-9d69-42e9-98ac-4e9403091b3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjU1NjcsIm5iZiI6MTcyNTI2NTI2NywicGF0aCI6Ii8xMTQ4ODcyODYvMzYzNTIwNzI2LWUxNTgxMDQ5LTlkNjktNDJlOS05OGFjLTRlOTQwMzA5MWIzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQwODIxMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzFjNGE4NjNjNzBmNDI4NzFlNzcwNTUyZDRmOWZhODllYjM2MmJlNGQ5NGRjMjJjZTMzNjM2ZmMwNmUyYzk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TS4L8O8UkWOZhGQiVGhZ_VCF2pdz0wXDd-m8j0cSrLw) ![Screenshot_20240901_223502](https://private-user-images.githubusercontent.com/114887286/363520727-4d67b49f-15e8-4447-9a8d-cbec941e4c6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjU1NjcsIm5iZiI6MTcyNTI2NTI2NywicGF0aCI6Ii8xMTQ4ODcyODYvMzYzNTIwNzI3LTRkNjdiNDlmLTE1ZTgtNDQ0Ny05YThkLWNiZWM5NDFlNGM2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQwODIxMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zN2IzZjcwODkyMDFkYjEzNjhkZGUzODA2OWFjYTQxMzg2NGY3ODc4OGY1YjY1NTg3ZDJhM2Y0MjMyMjcxYTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1lZ7XYovmLK3UGKcG8GqcMdoT9H3ZoaJCnbodyY9fJ4)

?

**Comment by TheEt1234** [comment]
![image](https://github.com/user-attachments/assets/b7d66f8c-52c4-4fa6-b90b-6230fdfa2d82)
ok its explained in the quests, nothing to fix (besides the "more weirdness"

**Comment by ancientmarinerdev** [comment]
> ![image](https://private-user-images.githubusercontent.com/74461678/363620117-b7d66f8c-52c4-4fa6-b90b-6230fdfa2d82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjc0NzUsIm5iZiI6MTcyNTI2NzE3NSwicGF0aCI6Ii83NDQ2MTY3OC8zNjM2MjAxMTctYjdkNjZmOGMtNTJjNC00ZmE2LWI5MGItNjIzMGZkZmEyZDgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA4NTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZWIyMDQ2MjI3MTgzMDA3ZmNkOWZkNjRjZDUyZDVlZmM1NzY4MjM1NTE2MDk3OWM3YTMwYWIwY2ZjNWM4NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mu0MDPAfW2zfCHFvYqoVuAHgPEXnFHk6Ks6WaXTJuDE) ok its explained in the quests, nothing to fix (besides the "more weirdness"

The crusher bug is causing it. Basically, I'm trying to feed the pebble slot, buy an iron element is going in there. It should not accept a mineral in pebble slot. It only backs up because of that.

Secondly other tubes are spitting items outside the pipes which is not expected. So there is 2 bugs there.

**Comment by TheEt1234** [comment]
> Fine so far, right, however, now, when the crusher completes, it sometimes puts the ores in the pebbles slot,

OH i didnt notice that im so sorry

**Comment by TheEt1234** [comment]
could you tell me more about the crusher bug (how to reproduce it)

**Comment by TheEt1234** [comment]
wait this just happened to me now... with an unknown node.... weird

**Comment by TheEt1234** [comment]
but *only* with unknown items... everything else works normally

**Comment by TheEt1234** [comment]
and crusher doesn't have any code to put anything in the input slot, so it's not a crusher bug

**Comment by ancientmarinerdev** [comment]
![Screenshot_20240902_174215](https://github.com/user-attachments/assets/cf1846f7-5108-4bbc-afb1-4187ccb6f0e8)
![Screenshot_20240902_174142](https://github.com/user-attachments/assets/b60df9e7-265d-4302-8129-c4d2de615d2b)

I think it's due to a full output for the auto-injector. I think it tries to pass the item on, fails and sends it back.

I'm also getting weird stuff where on my:

puncher -> auto-injector -> storinator

When the storinator is full, it keeps producing, and pushing to the auto-injector. As I remove say 10 stacks from the chest, it keeps putting more in the storinator so it's full within seconds. I think items go into limbo in the auto-injector and build up there. If they cannot go to output, I'm guessing they go back to where they came out of.

**Comment by ancientmarinerdev** [comment]
I don't think the auto-injector should try and pull if there is no space to push stuff.

**Comment by ancientmarinerdev** [comment]
If you see the first screenshot in this though:

https://github.com/ChefZander/skyblock_zero/issues/36#issuecomment-2323505670

They're filter injectors from matter extractors, and there is space in the chest, yet the matter has clipped out of the tube which it never used to do.

**Comment by TheEt1234** [comment]
> If they cannot go to output, I'm guessing they go back to where they came out of.

Oh thats weird..... let me check if regular pipeworks has this problem

**Comment by ancientmarinerdev** [comment]
![Screenshot_20240902_175149](https://github.com/user-attachments/assets/950e76ca-0907-4739-b7f6-5b7aed48278b)
If you see this image, the storinator at the top should only receive matter blobs (made from first auto-crafter), (the second makes pebbles), yet somehow, minerals crushed from pebbles ended up in that chest. There is a weird backflow thing going on which should not happen.

**Comment by TheEt1234** [comment]
i see now

**Comment by TheEt1234** [comment]
pipeworks has this same problem too, and i will give you a consistant setup to reproduce it shortly

**Comment by TheEt1234** [comment]
![image](https://github.com/user-attachments/assets/3d353dde-a003-4c66-8175-b84ad2c7516d)
im back, Chest A has some items it wants to push
Chest B is full
when it tries to push, the stuff first tries to go to chest b, then after some delay, ends up back in chest A

**Comment by TheEt1234** [comment]
the reason this is *super problematic* for crushers is because the output inventory is different than the input inventory

so it transfers stuff from the input to the output

**Comment by TheEt1234** [comment]
the obvious solution for this (handle your overflows):
![image](https://github.com/user-attachments/assets/8dbb1747-88d2-4c22-a575-70f2fcffe98b)

**Comment by TheEt1234** [comment]
Or just put up an infinite storinator and hope you will never get 5 000 stacks of random chemicals

**Comment by TheEt1234** [comment]
so, the solution to the *crusher bug*: manage your overflow correctly

**Comment by TheEt1234** [comment]
> I don't think the auto-injector should try and pull if there is no space to push stuff.

But this is a good idea

**Comment by TheEt1234** [comment]
so instead, i will just make the crusher only accept pebbles

**Comment by TheEt1234** [comment]
> If you see the first screenshot in this though:
> 
> [#36 (comment)](https://github.com/ChefZander/skyblock_zero/issues/36#issuecomment-2323505670)
> 
> They're filter injectors from matter extractors, and there is space in the chest, yet the matter has clipped out of the tube which it never used to do.

oh i *now* saw the matter. yeah that's *super* weird, i don't understand much of pipeworks's entity code 

does it end up in that chest?

does it happen consistently?

`and also, note: tube routing like this isnt very efficent *at large scales* as the items just wander around  the tubes, consider putting up some high priority tubes near the storinator and low priority tubes from locations that are away from the storinator if you expand this`

what happens if you break+place the tube?

**Comment by ancientmarinerdev** [comment]
My feeling is it was to do with puncher, and the fact it stocked up stuff that got stick in the injector. I'm guessing the extra item entities may have had an effect on performance. Not sure for certain though. I've cleared it out and it seems ok for now, but I'll see have to keep an eye on it.

That crusher input change will definitely help. If it ends up crushing more stuff, I guess it can change to a group. :)

**Comment by ancientmarinerdev** [comment]
If I have automation set up and I put empty water vials in, they just get spat out quickly. I'm wondering if maybe we need an extra input slot for empty liquid containers.

**Comment by TheEt1234** [comment]
> My feeling is it was to do with puncher, and the fact it stocked up stuff that got stick in the injector. I'm guessing the extra item entities may have had an effect on performance. Not sure for certain though. I've cleared it out and it seems ok for now, but I'll see have to keep an eye on it.
> 
> That crusher input change will definitely help. If it ends up crushing more stuff, I guess it can change to a group. :)

see https://github.com/mt-mods/pipeworks/issues/135 maybe?

and also, punchers don't need injectors, neither do node breakers

**Comment by TheEt1234** [comment]
also the real way to fix the crusher issue is to *handle your overflows*

**Comment by ChefZander** [comment]
Is this resolved?

**Comment by TheEt1234** [comment]
> Is this resolved?

no, but its very low priority

**Comment by ChefZander** [comment]
> > Is this resolved?
> 
> no, but its very low priority

What's the issue?

**Comment by TheEt1234** [comment]
> > > Is this resolved?
> > 
> > 
> > no, but its very low priority
> 
> What's the issue?

ive only reproduced this one: https://github.com/mt-mods/pipeworks/issues/135

**Comment by TheEt1234** [comment]
I can't do anything about this, only "upstream" pipeworks can, i don't know pipeworks code nearly as well as them, issue should be closed
