### ISSUE TITLE
Balancing issues

### ISSUE THREAD

**Issue by ancientmarinerdev** [ChefZander/skyblock_zero#42]
- [ ] Emittrium stacks of 16 are pure cruelty against punchers. You set up puncher -> filter injector -> chest, and it's full of rubbish and barely anything good within seconds. It's a raw resource, and most raw resource stacks 256. Even if you don't want it to be that much, even 128 would be preferable.
- [ ] Simple charged field should be craftable back into 9 charged particle
- [ ] Core dust should have a way to store itself in compact form and craftable back from this compact form
- [ ] Core dust should have more of a usage, once you get automation set up, it's pointless trash. Maybe slightly better tools could be using the compact form of core dust maybe
- [ ] Charge particle should have more of a usage

**Comment by theidealist101** [comment]
I agree with these, plus matter blobs should be craftable into matter dust. Remember though that core dust is used by generators.

**Comment by birdlover32767** [comment]
i agree with all of these, for the "compact core dust" task i propose a core immitator which can be punched 3 times before dissapearing

it can also be crafted from 9 core dust and into 9 core dust

**Comment by TheEt1234** [comment]
> You set up puncher -> filter injector -> chest, and it's full of rubbish and barely anything good within seconds

puncher -> filter injector -> item filter

item filter:
- if item is emittrium, put it in red
- if item is something else, put it in blue

red -> trashcan OR chest

blue -> trashcan OR chest (a different chest from the red one)

(item voids have the priority of 1, storinators have much higher priority than trashcans, so it will first attempt to go to the storinator, if it fails, it will go to the item void)
or did i name it the item sorter i forgot

**Comment by TheEt1234** [comment]
>  Core dust should have more of a usage, once you get automation set up, it's pointless trash. Maybe slightly better tools could be using the compact form of core dust maybe

I don't think it's pointless trash as you can use it for easy power in simple charged generators

i agree, when i get around to making emittrium reactors, i will also give core dust a use (in crafting of emittrium reactors maybe)

>  Charge particle should have more of a usage

same with this

**Comment by TheEt1234** [comment]
maybe the recipe of pebbles should change too?

**Comment by birdlover32767** [comment]
if you think about it core dust is used in circuits and antimatter but only like 10 times

**Comment by birdlover32767** [comment]
btw emittrium stack size is resolved in the latest version

**Comment by TheEt1234** [comment]
im currently hyper focused on making logic soo

**Comment by birdlover32767** [comment]
im trying to rework crafting to allow for more types but the crafting guide will not cooperate

**Comment by TheEt1234** [comment]
> im trying to rework crafting to allow for more types but the crafting guide will not cooperate

change the crafting guide

**Comment by birdlover32767** [comment]
i did but i can't get custom recipes to work properly

(in my own copy) i changed powder to be visible in the craftguide and added crushing recipes but the crushing recipes are only visible from pebbles

**Comment by TheEt1234** [comment]
> i did but i can't get custom recipes to work properly
> 
> (in my own copy) i changed powder to be visible in the craftguide and added crushing recipes but the crushing recipes are only visible from pebbles

why not

just add your custom system into the craftguide
also ingots polute the hell out of the craftguide (chem was a mistake)

**Comment by birdlover32767** [comment]
well still it should be flexible enough (in the future) to handle stuff like fiberweed -> 2CO2 aka custom formspecs

but im feeling too lazy to code it

**Comment by TheEt1234** [comment]
i think i should just merge the inventory and the craftguide like unified inventory (or just... use a heavily modified unified inventory)

because having craftguide and crafting be seperate is *insanely* annoying

**Comment by birdlover32767** [comment]
yea
you can copy sbz_base/crafting.lua in my crafting_types branch if you want to

**Comment by TheEt1234** [comment]
i think this is solved
