### ISSUE TITLE
Core can be protected with large protector blocks

### ISSUE THREAD

**Issue by birdlover32767** [ChefZander/skyblock_zero#46]
self-explanatory title
image if you somehow can't understand this:
![screenshot_20240914_003813](https://github.com/user-attachments/assets/9d1e5561-cb58-4049-a73e-689695087401)

**Comment by TheEt1234** [comment]
oh crap :/

**Comment by TheEt1234** [comment]
you sure you dont have /grantme all?

**Comment by TheEt1234** [comment]
try it with only the regular privs

**Comment by TheEt1234** [comment]
try it with only the regular privs

**Comment by birdlover32767** [comment]
k

**Comment by birdlover32767** [comment]
![screenshot_20240914_114151](https://github.com/user-attachments/assets/4a69524e-8fb8-4353-a2a3-dbb14dd37858)

**Comment by TheEt1234** [comment]
crap

**Comment by TheEt1234** [comment]
todo for me: fix this

**Comment by TheEt1234** [comment]
ok i will actually fix it
