### ISSUE TITLE
`unlock_achievement` can unlock type="text" quests

### ISSUE THREAD

**Issue by birdlover32767** [ChefZander/skyblock_zero#47]
if you want to fix this then refactor the questbook while you're at it

**Comment by TheEt1234** [comment]
the questbook desperately needs a rewrite LOL

**Comment by ChefZander** [comment]
All was working on it but then abandoned, i dont feel like this is an urgent issue since it doesnt really matter and the questbook is fine as-is. If someone wants to take a rewrite upon themselves, then make sure it doesnt break anything and it actually better than the current one lol
