### ISSUE TITLE
Quest's Crusher and Generators dosent work

### ISSUE THREAD

**Issue by slepice24** [ChefZander/skyblock_zero#48]
Quest's Crusher and Generators dosent work

![screenshot_20240914_201342](https://github.com/user-attachments/assets/94779407-350e-4c69-9664-369a55a97bb1)
![screenshot_20240914_201346](https://github.com/user-attachments/assets/7f69d62e-ce4c-4cbe-97d8-79d6493dd23b)

same with Generators

**Comment by TheEt1234** [comment]
are you on the bleeding edge version or contentdb version

**Comment by slepice24** [comment]
yes contentdb version

**Comment by TheEt1234** [comment]
(this should be fixed in the absolute latest version)

**Comment by slepice24** [comment]
ok thanks i will try it

**Comment by TheEt1234** [comment]
zander made a cdb release just now that should fix it, also did it work

**Comment by slepice24** [comment]
yes it fixed it

**Comment by TheEt1234** [comment]
amazing
