### ISSUE TITLE
any machine + connector = crash (CDB version)

### ISSUE THREAD

**Issue by slepice24** [ChefZander/skyblock_zero#49]
when placed connector next to any machine something like this and turned on

![screenshot_20240915_121625](https://github.com/user-attachments/assets/a51e4af9-a77f-4834-8074-61b003bbd23b)

it crashes until turned off
output:
AsyncErr: Lua: Runtime error from mod 'sbz_power' in callback environment_Step(): /app/share/minetest/builtin/common/misc_helpers.lua:497: attempt to get length of local 'other' (a number value)
stack traceback:
	/app/share/minetest/builtin/common/misc_helpers.lua:497: in function 'insert_all'
	...netest/games/skyblock_zero/mods/sbz_power/connectors.lua:69: in function 'assemble'
	...games/skyblock_zero/mods/sbz_power/switching_station.lua:72: in function 'func'
	...games/skyblock_zero/mods/sbz_power/switching_station.lua:12: in function 'iterate_around_pos'
	...games/skyblock_zero/mods/sbz_power/switching_station.lua:77: in function 'func'
	...games/skyblock_zero/mods/sbz_power/switching_station.lua:12: in function 'iterate_around_pos'
	...games/skyblock_zero/mods/sbz_power/switching_station.lua:77: in function 'func'
	...games/skyblock_zero/mods/sbz_power/switching_station.lua:12: in function 'iterate_around_pos'
	...games/skyblock_zero/mods/sbz_power/switching_station.lua:77: in function 'func'
	...games/skyblock_zero/mods/sbz_power/switching_station.lua:12: in function 'iterate_around_pos'
	...
	...games/skyblock_zero/mods/sbz_power/switching_station.lua:12: in function 'iterate_around_pos'
	...games/skyblock_zero/mods/sbz_power/switching_station.lua:77: in function 'func'
	...games/skyblock_zero/mods/sbz_power/switching_station.lua:12: in function 'iterate_around_pos'
	...games/skyblock_zero/mods/sbz_power/switching_station.lua:77: in function 'func'
	...games/skyblock_zero/mods/sbz_power/switching_station.lua:12: in function 'iterate_around_pos'
	...games/skyblock_zero/mods/sbz_power/switching_station.lua:77: in function 'internal'
	...games/skyblock_zero/mods/sbz_power/switching_station.lua:81: in function 'assemble_network'
	...games/skyblock_zero/mods/sbz_power/switching_station.lua:142: in function 'switching_station_tick'
	...games/skyblock_zero/mods/sbz_power/switching_station.lua:339: in function <...games/skyblock_zero/mods/sbz_power/switching_station.lua:309>
	/app/share/minetest/builtin/common/register.lua:26: in function </app/share/minetest/builtin/common/register.lua:12>

**Comment by TheEt1234** [comment]
i think i broke this one (probably has something to do with me completely changing the switching station code...) i'll try reproducing it

**Comment by TheEt1234** [comment]
yep, ive been able to reproduce it

**Comment by TheEt1234** [comment]
and i think i have fixed it, but connectors may still be very broken

**Comment by TheEt1234** [comment]
nevermind, they seem to work, i will PR the fix
