### ISSUE TITLE
High Power Electric Furnace doesn't rotate propertly

### ISSUE THREAD

**Issue by TheEt1234** [ChefZander/skyblock_zero#51]
1) Place hpef
2) Observe that it only rotates in one way

hpef HAS `paramtype2 = "4dir"`

and it also does `node.param2 = node.param2 + 1`

**Comment by TheEt1234** [comment]
so idk whats the issue, but ill fix it after logic

**Comment by TheEt1234** [comment]
oh god i need to fix this

**Comment by birdlover32767** [comment]
fix it now then

**Comment by TheEt1234** [comment]
> fix it now then

ok so it works on my machine

**Comment by TheEt1234** [comment]
does it work for you?

**Comment by birdlover32767** [comment]
well it works but you can change the hpef tiles to this:
```lua
{
    "hpef_top.png",
    "hpef_top.png",
    "hpef_top.png",
    "hpef_top.png",
    "hpef_top.png",
    "hpef_front_off.png",
},
```

**Comment by TheEt1234** [comment]
ok

**Comment by TheEt1234** [comment]
so i guess its solved??
