### ISSUE TITLE
Can't place Matter Blob

### ISSUE THREAD

**Issue by mark-wiemer** [ChefZander/skyblock_zero#67]
I just started, only the core exists, and I've made a matter blob. It's in my hand, but left-clicking or right-clicking on any side of the core just digs. Jumping and clicking on top of the core digs. Same for bottom. Clicking into space does nothing. Q just drops. Help! I wanna play :(

**Comment by ChefZander** [comment]
I saw this was already solved in the discord but for anyone stumbling on this: a crouch+right click does the trick. -Zander
