### ISSUE TITLE
Jetpacks can change itemstack textures of non-jetpacks

### ISSUE THREAD

**Issue by birdlover32767** [ChefZander/skyblock_zero#75]

**Comment by TheEt1234** [comment]
ok what

**Comment by birdlover32767** [comment]
1. activate the jetpack
2. swap to another item while jetpack is active

**Comment by TheEt1234** [comment]
oh... how have i not encountered this... anyway fix is trivial

**Comment by TheEt1234** [comment]
This has been fixed, please close this issue
