### ISSUE TITLE
You can get "Emptiness" without falling*

### ISSUE THREAD

**Issue by The4codeblocks** [ChefZander/skyblock_zero#78]
Source image:
![image](https://github.com/user-attachments/assets/475c08ae-72ff-4a91-8a0e-03e2f49410d0)
(From unofficial SBZ server)

*without triggering the "you fell" event that teleports you to core

**Comment by TheEt1234** [comment]
thats probably intentional

**Comment by The4codeblocks** [comment]
> thats probably intentional

probably

**Comment by The4codeblocks** [comment]
![image](https://github.com/user-attachments/assets/3cb53ce4-eaf0-440c-85c7-846a8bedd1ee)
the code looks like it's intentional, but who am I to assume

**Comment by TheEt1234** [comment]
probably should close this

**Comment by The4codeblocks** [comment]
> probably should close this

yeh
